name = "rakyzu-website"
compatibility_date = "2026-07-29"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "rakyzu-db"
database_id = ""

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "rakyzu-assets"
