name = "rakyzu-website"
compatibility_date = "2026-07-29"

[[d1_databases]]
binding = "rakyzu_db"
database_name = "rakyzu-db"
database_id = "4faee161-5d2e-4b09-b3ff-255159bbac96"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "rakyzu-assets"

send_email = [
  { name = "EMAIL", address = "zulhampratama@rakyzu.my.id" }
]
